version: "3.7"
services:
    osrm:
        build: 
            context: ./osrm
            args:
                PBF: https://download.geofabrik.de/europe/bulgaria-latest.osm.pbf
        container_name: osrm
        ports:
        - "5000:5000"

    carpooly-frontend:
        build: .
        container_name: carpooly-frontend
        ports:
            - 4200:4200
        links:
            - osrm